### ISSUE TITLE
Why I got a error when I try to use my dataset like that: batchSize * outputVolume < std::numeric_limits<int>::max() assert faild. due to limits of cuda hash, the volume of dense space include batch size must less than std::numeric_limits<int>::max() = 2e9

### ISSUE THREAD

**Issue by Cat-Lover-Yes** [hustvl/HAIS#37]

**Comment by Cat-Lover-Yes** [comment]
Traceback (most recent call last):
  File "/home/ydf/HAIS/train.py", line 215, in <module>
    train_epoch(dataset.train_data_loader, model, model_fn, optimizer, epoch)
  File "/home/ydf/HAIS/train.py", line 65, in train_epoch
    loss, _, visual_dict, meter_dict = model_fn(batch, model, epoch)
  File "/home/ydf/HAIS/model/hais/hais.py", line 425, in model_fn
    ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch, 'train')
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ydf/HAIS/model/hais/hais.py", line 274, in forward
    output = self.input_conv(input)
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/spconv/modules.py", line 134, in forward
    input = module(input)
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/spconv/conv.py", line 169, in forward
    outids, indice_pairs, indice_pair_num = ops.get_indice_pairs(
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/spconv/ops.py", line 91, in get_indice_pairs
    res = torch.ops.spconv.get_indice_pairs(indices, batch_size, out_shape,
  File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: /home/ydf/HAIS/lib/spconv/src/spconv/spconv_ops.cc 40
batchSize * outputVolume < std::numeric_limits<int>::max() assert faild. due to limits of cuda hash, the volume of dense space include batch size must less than std::numeric_limits<int>::max() = 2e9

**Comment by Cat-Lover-Yes** [comment]
> Traceback (most recent call last): File "/home/ydf/HAIS/train.py", line 215, in train_epoch(dataset.train_data_loader, model, model_fn, optimizer, epoch) File "/home/ydf/HAIS/train.py", line 65, in train_epoch loss, _, visual_dict, meter_dict = model_fn(batch, model, epoch) File "/home/ydf/HAIS/model/hais/hais.py", line 425, in model_fn ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch, 'train') File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/ydf/HAIS/model/hais/hais.py", line 274, in forward output = self.input_conv(input) File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/spconv/modules.py", line 134, in forward input = module(input) File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/spconv/conv.py", line 169, in forward outids, indice_pairs, indice_pair_num = ops.get_indice_pairs( File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/spconv/ops.py", line 91, in get_indice_pairs res = torch.ops.spconv.get_indice_pairs(indices, batch_size, out_shape, File "/home/ydf/anaconda3/envs/mega/lib/python3.9/site-packages/torch/_ops.py", line 143, in **call** return self._op(*args, **kwargs or {}) RuntimeError: /home/ydf/HAIS/lib/spconv/src/spconv/spconv_ops.cc 40 batchSize * outputVolume < std::numeric_limits::max() assert faild. due to limits of cuda hash, the volume of dense space include batch size must less than std::numeric_limits::max() = 2e9

@outsidercsy  This is my error text.
