### ISSUE TITLE
help

### ISSUE THREAD

**Issue by SakuraTau** [hustvl/HAIS#43]

**Comment by SakuraTau** [comment]
Hi, thanks for your excellent work. I have the following problem when running train.py:
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMath.cu line=35 error=9 : invalid configuration argument
Traceback (most recent call last):
  File "/home/wang_yongjun/ws/code/HAIS/train.py", line 217, in <module>
    train_epoch(dataset.train_data_loader, model, model_fn, optimizer, epoch)
  File "/home/wang_yongjun/ws/code/HAIS/train.py", line 67, in train_epoch
    loss, _, visual_dict, meter_dict = model_fn(batch, model, epoch)
  File "/home/wang_yongjun/ws/code/HAIS/model/hais/hais.py", line 421, in model_fn
    ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch, 'train')
  File "/home/wang_yongjun/anaconda3/envs/hais/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wang_yongjun/ws/code/HAIS/model/hais/hais.py", line 323, in forward
    input_feats, inp_map = self.clusters_voxelization(proposals_idx, proposals_offset, output_feats, coords, self.score_fullscale, self.score_scale, self.score_mode)
  File "/home/wang_yongjun/ws/code/HAIS/model/hais/hais.py", line 223, in clusters_voxelization
    clusters_coords_min = hais_ops.sec_min(clusters_coords, clusters_offset.cuda())  # (nCluster, 3), float
  File "/home/wang_yongjun/ws/code/HAIS/lib/hais_ops/functions/hais_ops.py", line 405, in forward
    out = torch.cuda.FloatTensor(nProposal, C).zero_()
RuntimeError: cuda runtime error (9) : invalid configuration argument at /pytorch/aten/src/THC/generic/THCTensorMath.cu:35
How can I solve this problem?
Looking forward to your reply, thank you very much!
![PixPin_2024-06-04_19-15-22](https://github.com/hustvl/HAIS/assets/140884199/5e61cb70-2196-4943-be31-fee037df6a12)
