### ISSUE TITLE
Inference Problem

### ISSUE THREAD

**Issue by Nolansheng** [hustvl/HAIS#8]
Hello, when I want to inference the model by the code 'CUDA_VISIBL_DEVICES=1 python test.py --config config/hais_run1_scannet.yaml --pretrain hais_ckpt.pth', (I se the yaml config file correctly) but I got the error like this "Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from util.config import cfg
  File "/HAIS/util/config.py", line 30, in <module>
    cfg = get_parser()
  File "/HAIS/util/config.py", line 22, in get_parser
    config = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader' "

Do you know how to fix this? Thanks in advance.

**Comment by thangvubk** [comment]
I think downgrading pyyaml will resolve the problem.
``pip install pyyaml==5.4``
